2023/09/29 11:51:26 INFO mlflow.tracking.fluent: Experiment with name 'nanostring_cosmx_human_nsclc_reference_query_mapping' does not exist. Creating a new experiment.
Traceback (most recent call last):
  File "/lustre/groups/imm01/workspace/irene.bonafonte/Projects/2023May_nichecompass/nichecompass-reproducibility/scripts/reference_query/../map_query_on_nichecompass_reference_model.py", line 187, in <module>
    experiment = mlflow.set_experiment(
  File "/home/icb/irene.bonafonte/miniconda3/envs/nichecompass-reproducibility/lib/python3.9/site-packages/mlflow/tracking/fluent.py", line 123, in set_experiment
    experiment_id = client.create_experiment(experiment_name)
  File "/home/icb/irene.bonafonte/miniconda3/envs/nichecompass-reproducibility/lib/python3.9/site-packages/mlflow/tracking/client.py", line 616, in create_experiment
    return self._tracking_client.create_experiment(name, artifact_location, tags)
  File "/home/icb/irene.bonafonte/miniconda3/envs/nichecompass-reproducibility/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py", line 240, in create_experiment
    return self.store.create_experiment(
  File "/home/icb/irene.bonafonte/miniconda3/envs/nichecompass-reproducibility/lib/python3.9/site-packages/mlflow/store/tracking/file_store.py", line 371, in create_experiment
    self._validate_experiment_does_not_exist(name)
  File "/home/icb/irene.bonafonte/miniconda3/envs/nichecompass-reproducibility/lib/python3.9/site-packages/mlflow/store/tracking/file_store.py", line 363, in _validate_experiment_does_not_exist
    raise MlflowException(
mlflow.exceptions.MlflowException: Experiment 'nanostring_cosmx_human_nsclc_reference_query_mapping' already exists.
